import Phaser from "phaser";
import { boundedWorldCamera } from "@/games/_shared/camera/worldCamera";
import { readLocalGameValue,writeLocalGameValue } from "@/games/_shared/storage/localGameStorage";
import type { GameBridge,GameRuntimeController } from "@/games/_shared/types/runtime";
import { DATA_CENTER_WORLD,advanceDataCenter,createDataCenterState,currentWorkload,dataCenterLayout,dataCenterPrompt,dataCenterReady,dataCenterScore,dataCenterStats,interactDataCenter,type DataCenterEvent,type DataCenterState,type RackType } from "./model";
const BG=0x071019,FLOOR=0x101b26,GRID=0x1c3041,INK=0xeef6ff,GREEN=0x67e2b3,YELLOW=0xffce68,RED=0xff6c7a,CYAN=0x68d8ff; const COLORS:Record<RackType,number>={compute:0xffad57,network:0x68d8ff,power:0xffd66b,cooling:0x6be4d2,storage:0xc29cff};
function clock(s:number){const v=Math.max(0,Math.ceil(s));return`${Math.floor(v/60)}:${String(v%60).padStart(2,"0")}`;}
const DC_TIERS=["EDGE POD","AI HALL","HYPERSCALE HALL","MEGACAMPUS"] as const;
function dcTier(score:number){return score>=8200?3:score>=4700?2:score>=2100?1:0;}
export function mountGame(mount:HTMLElement,bridge:GameBridge):GameRuntimeController{let muted=false,audio:AudioContext|null=null,best=readLocalGameValue<number>(bridge.gameSlug,"high-score",1)??0;const tone=(f:number,d=.07)=>{if(muted||typeof window==="undefined")return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d);}catch{}};
 class Scene extends Phaser.Scene{private state!:DataCenterState;private g?:Phaser.GameObjects.Graphics;private keys:Record<string,Phaser.Input.Keyboard.Key>={};private left?:Phaser.GameObjects.Text;private right?:Phaser.GameObjects.Text;private prompt?:Phaser.GameObjects.Text;private detail?:Phaser.GameObjects.Text;private visual=0;constructor(){super("data-center-architect");}create(){this.g=this.add.graphics();this.left=this.add.text(14,12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",backgroundColor:"#071019df",padding:{x:8,y:5}}).setDepth(30);this.right=this.add.text(this.scale.width-14,12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",align:"right",backgroundColor:"#071019df",padding:{x:8,y:5}}).setOrigin(1,0).setDepth(30);this.prompt=this.add.text(this.scale.width/2,this.scale.height-12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"11px",fontStyle:"bold",backgroundColor:"#071019ef",padding:{x:8,y:5}}).setOrigin(.5,1).setDepth(31);this.detail=this.add.text(14,this.scale.height-12,"",{color:"#9fb0c0",fontFamily:"Arial",fontSize:"10px",backgroundColor:"#071019e8",padding:{x:7,y:5}}).setOrigin(0,1).setDepth(31);if(this.input.keyboard)this.keys=this.input.keyboard.addKeys("W,A,S,D,UP,DOWN,LEFT,RIGHT,E,SPACE,R") as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard?.on("keydown-E",()=>this.interact());this.input.keyboard?.on("keydown-SPACE",()=>this.interact());this.input.keyboard?.on("keydown-R",()=>this.reset());this.scale.on("resize",this.resize,this);this.reset();}update(_:number,d:number){if(this.state.mode!=="playing")return;this.visual+=d;const x=Number(Boolean(this.keys.D?.isDown||this.keys.RIGHT?.isDown))-Number(Boolean(this.keys.A?.isDown||this.keys.LEFT?.isDown)),y=Number(Boolean(this.keys.S?.isDown||this.keys.DOWN?.isDown))-Number(Boolean(this.keys.W?.isDown||this.keys.UP?.isDown));const r=advanceDataCenter(this.state,{x,y},d/1000);this.state=r.state;this.event(r.event);this.draw();}
 private projection(){const mobile=this.scale.width<620;if(!mobile)return{cameraX:DATA_CENTER_WORLD.width/2,cameraY:DATA_CENTER_WORLD.height/2,anchorX:this.scale.width/2,anchorY:this.scale.height/2+12,scale:Math.min((this.scale.width-42)/DATA_CENTER_WORLD.width,(this.scale.height-84)/DATA_CENTER_WORLD.height)};const scale=Math.max(.56,Math.min(.74,this.scale.width/535));return boundedWorldCamera({playerX:this.state.playerX,playerY:this.state.playerY,viewportWidth:this.scale.width,viewportHeight:this.scale.height,worldWidth:DATA_CENTER_WORLD.width,worldHeight:DATA_CENTER_WORLD.height,scale,anchorY:this.scale.height*.54});}
 private p(x:number,y:number){const c=this.projection();return{x:c.anchorX+(x-c.cameraX)*c.scale,y:c.anchorY+(y-c.cameraY)*c.scale};}
 private draw(){const g=this.g;if(!g)return;g.clear();g.fillStyle(BG,1).fillRect(0,0,this.scale.width,this.scale.height);const a=this.p(0,0),b=this.p(DATA_CENTER_WORLD.width,DATA_CENTER_WORLD.height),c=this.projection();g.fillStyle(FLOOR,1).fillRect(a.x,a.y,b.x-a.x,b.y-a.y);g.lineStyle(Math.max(.6,c.scale),GRID,.45);for(let x=0;x<=DATA_CENTER_WORLD.width;x+=80){const t=this.p(x,0),d=this.p(x,DATA_CENTER_WORLD.height);g.lineBetween(t.x,t.y,d.x,d.y);}for(let y=0;y<=DATA_CENTER_WORLD.height;y+=80){const l=this.p(0,y),r=this.p(DATA_CENTER_WORLD.width,y);g.lineBetween(l.x,l.y,r.x,r.y);}this.drawEnvironment();this.drawStaging();this.drawBays();this.drawStations();this.drawPlayer();const s=dataCenterStats(this.state),w=currentWorkload(this.state);this.left?.setText(`C ${s.compute}/${w.compute} · NET ${s.network}/${w.network} · ST ${s.storage}/${w.storage}\nPWR ${s.powerDraw}/${s.powerCapacity} · HEAT ${s.thermal}/${w.maxHeat} · RED ${s.redundancy}/${w.redundancy}`);this.right?.setText(`${clock(this.state.timeLeft)} RUN · ${DC_TIERS[dcTier(best)]}${this.state.workloadRunning?` · ${clock(this.state.workloadTime)} SLA`:""}\nDone ${this.state.completedWorkloads} · Rep ${Math.round(this.state.reputation)} · Best ${best}`);this.prompt?.setText(`${dataCenterPrompt(this.state)} · WASD/ARROWS + E`);this.detail?.setText(`${w.name.toUpperCase()}${dataCenterReady(this.state)?" · READY":" · BUILDING"}${this.state.faultSlot!==null?` · FAULT BAY ${this.state.faultSlot+1}`:""}\nUptime ${this.state.uptime.toFixed(0)}s · Breach ${this.state.slaBreaches.toFixed(1)}s · Score ${dataCenterScore(this.state)}`);mount.dataset.dcX=this.state.playerX.toFixed(1);mount.dataset.dcY=this.state.playerY.toFixed(1);mount.dataset.dcCarried=this.state.carried??"";mount.dataset.dcSlots=String(this.state.slots.filter(Boolean).length);mount.dataset.dcReady=dataCenterReady(this.state)?"true":"false";mount.dataset.dcRunning=this.state.workloadRunning?"true":"false";mount.dataset.dcCompleted=String(this.state.completedWorkloads);mount.dataset.dcFault=this.state.faultSlot===null?"":String(this.state.faultSlot);mount.dataset.dcKit=this.state.carryingRepairKit?"true":"false";mount.dataset.dcMode=this.state.mode;}
 private drawEnvironment(){const g=this.g;if(!g)return;const s=this.projection().scale,tier=dcTier(best),pulse=.5+.35*Math.sin(this.visual/330);
  for(const y of [155,360,565]){const a=this.p(430,y),b=this.p(1035,y);g.fillStyle(y===360?0x1d2430:0x132733,.72).fillRoundedRect(a.x,a.y-38*s,b.x-a.x,76*s,8*s);g.lineStyle(2*s,y===360?RED:CYAN,.16).lineBetween(a.x,a.y,b.x,a.y);}
  const busA=this.p(420,92),busB=this.p(1040,92);g.lineStyle(8*s,0x29343b,.9).lineBetween(busA.x,busA.y,busB.x,busB.y);g.lineStyle(2*s,YELLOW,.42).lineBetween(busA.x,busA.y,busB.x,busB.y);
  const fiberA=this.p(430,690),fiberB=this.p(1030,690);g.lineStyle(3*s,CYAN,.32).lineBetween(fiberA.x,fiberA.y,fiberB.x,fiberB.y);
  for(let x=470;x<=1010;x+=90){const q=this.p(x,690);g.fillStyle(CYAN,.28+pulse*.18).fillCircle(q.x,q.y,4*s);}
  const noc=this.p(300,135);g.fillStyle(0x101b24,.98).fillRoundedRect(noc.x-55*s,noc.y-35*s,110*s,70*s,7*s);g.lineStyle(2*s,CYAN,.42).strokeRoundedRect(noc.x-55*s,noc.y-35*s,110*s,70*s,7*s);for(let i=0;i<5;i++)g.fillStyle(i<tier+2?GREEN:GRID,.55).fillCircle(noc.x+(-36+i*18)*s,noc.y+17*s,4*s);
  if(tier>=1){for(let i=0;i<tier;i++){const q=this.p(1120,330+i*92);g.fillStyle(0x15242e,.95).fillRoundedRect(q.x-45*s,q.y-30*s,90*s,60*s,6*s);g.lineStyle(2*s,GREEN,.28+.12*pulse).strokeRoundedRect(q.x-45*s,q.y-30*s,90*s,60*s,6*s);}}
 }
 private drawStaging(){const g=this.g;if(!g)return;for(const id of Object.keys(dataCenterLayout.staging) as RackType[]){const q=dataCenterLayout.staging[id],p=this.p(q.x,q.y),s=this.projection().scale,color=COLORS[id];g.fillStyle(0x0d1922,.98).fillRoundedRect(p.x-40*s,p.y-37*s,80*s,74*s,6);g.lineStyle(2,color,.78).strokeRoundedRect(p.x-40*s,p.y-37*s,80*s,74*s,6);for(let u=0;u<4;u++){g.fillStyle(0x172936,1).fillRect(p.x-30*s,p.y+(-24+u*14)*s,60*s,7*s);g.fillStyle(color,.55).fillCircle(p.x+25*s,p.y+(-21+u*14)*s,2.6*s);}g.fillStyle(color,.08).fillCircle(p.x,p.y,47*s);}}
 private drawBays(){const g=this.g;if(!g)return;this.state.slots.forEach((id,i)=>{const q=dataCenterLayout.slots[i],p=this.p(q.x,q.y),s=this.projection().scale,fault=this.state.faultSlot===i,color=id?COLORS[id]:0x516474;g.fillStyle(0x08121a,.98).fillRoundedRect(p.x-49*s,p.y-65*s,98*s,130*s,7);g.lineStyle(fault?4:2,fault?RED:color,fault?1:.72).strokeRoundedRect(p.x-49*s,p.y-65*s,98*s,130*s,7);g.fillStyle(0x152430,.95).fillRect(p.x-41*s,p.y-56*s,82*s,112*s);
    if(id){for(let u=0;u<7;u++){const yy=p.y+(-47+u*15)*s;g.fillStyle(0x0a151d,.98).fillRoundedRect(p.x-34*s,yy,68*s,9*s,2*s);g.fillStyle(color,.45+.18*Math.sin(this.visual/280+u)).fillCircle(p.x+28*s,yy+4*s,2.5*s);}if(id==="compute"){for(let f=0;f<2;f++){const fx=p.x+(-18+f*36)*s,fy=p.y+47*s;g.lineStyle(1.5*s,color,.5).strokeCircle(fx,fy,8*s);const ang=this.visual/260+f;g.lineBetween(fx,fy,fx+Math.cos(ang)*7*s,fy+Math.sin(ang)*7*s);}}}
    if(fault)g.lineStyle(3,RED,.28+.32*Math.sin(this.visual/100)).strokeCircle(p.x,p.y,72*s);
    if(id==="compute"&&this.state.slots.some((v,j)=>v==="cooling"&&Math.hypot(dataCenterLayout.slots[j].x-q.x,dataCenterLayout.slots[j].y-q.y)<230))g.lineStyle(2,CYAN,.55).strokeCircle(p.x,p.y,60*s);
  });}
 private drawStations(){const d=this.p(dataCenterLayout.deploy.x,dataCenterLayout.deploy.y),r=this.p(dataCenterLayout.repair.x,dataCenterLayout.repair.y),s=this.projection().scale,g=this.g;if(!g)return;g.fillStyle(0x10251f,.98).fillRoundedRect(d.x-48*s,d.y-37*s,96*s,74*s,7*s);g.lineStyle(2,GREEN,.78).strokeRoundedRect(d.x-48*s,d.y-37*s,96*s,74*s,7*s);for(let i=0;i<3;i++)g.fillStyle(GREEN,.25+i*.13).fillRect(d.x-31*s,d.y+(-20+i*17)*s,62*s,8*s);g.fillStyle(0x292514,.98).fillRoundedRect(r.x-45*s,r.y-35*s,90*s,70*s,7*s);g.lineStyle(2,YELLOW,.75).strokeRoundedRect(r.x-45*s,r.y-35*s,90*s,70*s,7*s);g.fillStyle(YELLOW,.6).fillRoundedRect(r.x-23*s,r.y-9*s,46*s,18*s,3*s);}
 private drawPlayer(){const p=this.p(this.state.playerX,this.state.playerY),s=this.projection().scale,g=this.g;if(!g)return;g.fillStyle(0x020405,.5).fillEllipse(p.x+2*s,p.y+13*s,28*s,9*s);g.fillStyle(0xbed2e2,1).fillRoundedRect(p.x-9*s,p.y-7*s,18*s,26*s,6*s);g.fillStyle(INK,1).fillCircle(p.x,p.y-12*s,9*s);g.fillStyle(CYAN,.55).fillRoundedRect(p.x-6*s,p.y-14*s,12*s,5*s,2*s);if(this.state.carried){g.fillStyle(COLORS[this.state.carried],1).fillRoundedRect(p.x+9*s,p.y-10*s,16*s,17*s,2*s);g.lineStyle(1*s,0x0a141b,.7).strokeRoundedRect(p.x+9*s,p.y-10*s,16*s,17*s,2*s);}if(this.state.carryingRepairKit)g.fillStyle(YELLOW,1).fillRoundedRect(p.x-25*s,p.y-9*s,14*s,12*s,2*s);}
 private interact(){const r=interactDataCenter(this.state);this.state=r.state;this.event(r.event);this.draw();}
 private event(e:DataCenterEvent){if(e==="rack_picked")tone(540);else if(e==="rack_placed"){tone(680);bridge.emit("game_action",{action:"rack_placed",slots:this.state.slots.filter(Boolean).length});}else if(e==="deploy_started"){tone(820,.12);bridge.emit("level_completed",{action:"workload_deployed",workload:currentWorkload(this.state).id});bridge.setStatus("Workload live — keep SLA capacity green while failures arrive");}else if(e==="deploy_blocked")tone(180);else if(e==="fault"){tone(145,.15);bridge.setStatus(`Rack fault in bay ${(this.state.faultSlot??0)+1} — get the repair kit`);}else if(e==="repair_started")tone(720);else if(e==="workload_complete")tone(880,.13);else if(e==="session_complete")this.end();}
 private end(){const score=dataCenterScore(this.state),oldTier=dcTier(best);best=Math.max(best,score);const newTier=dcTier(best);writeLocalGameValue(bridge.gameSlug,"high-score",1,best);bridge.emit("game_over",{score,completed_workloads:this.state.completedWorkloads,uptime:this.state.uptime,sla_breach_seconds:this.state.slaBreaches,campus_tier:newTier});if(newTier>oldTier){bridge.emit("game_action",{action:"campus_tier_up",tier:newTier});bridge.setStatus(`Campus upgraded — ${DC_TIERS[newTier]} unlocked for future runs`);}else bridge.setStatus(`Data center run complete · ${this.state.completedWorkloads} workloads · score ${score}`);}
 private reset(){const tier=dcTier(best),next=createDataCenterState((Date.now()^0x45c0de)>>>0);next.budget+=tier*10;next.faultTimer+=tier*4;this.state=next;this.draw();bridge.setStatus(`Data Center Architect live — ${DC_TIERS[tier]} · install racks, deploy workloads, and repair failures`);bridge.emit("game_started",{mode:"walkable-data-center",campus_tier:tier});}private resize(){this.right?.setPosition(this.scale.width-14,12);this.prompt?.setPosition(this.scale.width/2,this.scale.height-12);this.detail?.setPosition(14,this.scale.height-12);this.draw();}}
 const game=new Phaser.Game({type:Phaser.AUTO,parent:mount,backgroundColor:BG,scene:[Scene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,pixelArt:false}});return{pause(){game.scene.pause("data-center-architect");bridge.setStatus("Paused");},resume(){game.scene.resume("data-center-architect");bridge.setStatus("Data Center Architect resumed");},restart(){game.scene.stop("data-center-architect");game.scene.start("data-center-architect");},setMuted(v:boolean){muted=v;},destroy(){game.destroy(true);void audio?.close();audio=null;}} satisfies GameRuntimeController;
}
