import Phaser from "phaser";
import { boundedWorldCamera } from "@/games/_shared/camera/worldCamera";
import { readLocalGameValue,writeLocalGameValue } from "@/games/_shared/storage/localGameStorage";
import type { GameBridge,GameRuntimeController } from "@/games/_shared/types/runtime";
import { DATA_CENTER_WORLD,advanceDataCenter,createDataCenterState,currentWorkload,dataCenterLayout,dataCenterPrompt,dataCenterReady,dataCenterScore,dataCenterStats,interactDataCenter,type DataCenterEvent,type DataCenterState,type RackType } from "./model";
const BG=0x071019,FLOOR=0x101b26,GRID=0x1c3041,INK=0xeef6ff,GREEN=0x67e2b3,YELLOW=0xffce68,RED=0xff6c7a,CYAN=0x68d8ff; const COLORS:Record<RackType,number>={compute:0xffad57,network:0x68d8ff,power:0xffd66b,cooling:0x6be4d2,storage:0xc29cff};
function clock(s:number){const v=Math.max(0,Math.ceil(s));return`${Math.floor(v/60)}:${String(v%60).padStart(2,"0")}`;}
export function mountGame(mount:HTMLElement,bridge:GameBridge):GameRuntimeController{let muted=false,audio:AudioContext|null=null,best=readLocalGameValue<number>(bridge.gameSlug,"high-score",1)??0;const tone=(f:number,d=.07)=>{if(muted||typeof window==="undefined")return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d);}catch{}};
 class Scene extends Phaser.Scene{private state!:DataCenterState;private g?:Phaser.GameObjects.Graphics;private keys:Record<string,Phaser.Input.Keyboard.Key>={};private left?:Phaser.GameObjects.Text;private right?:Phaser.GameObjects.Text;private prompt?:Phaser.GameObjects.Text;private detail?:Phaser.GameObjects.Text;constructor(){super("data-center-architect");}create(){this.g=this.add.graphics();this.left=this.add.text(14,12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",backgroundColor:"#071019df",padding:{x:8,y:5}}).setDepth(30);this.right=this.add.text(this.scale.width-14,12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",align:"right",backgroundColor:"#071019df",padding:{x:8,y:5}}).setOrigin(1,0).setDepth(30);this.prompt=this.add.text(this.scale.width/2,this.scale.height-12,"",{color:"#eef6ff",fontFamily:"Arial",fontSize:"11px",fontStyle:"bold",backgroundColor:"#071019ef",padding:{x:8,y:5}}).setOrigin(.5,1).setDepth(31);this.detail=this.add.text(14,this.scale.height-12,"",{color:"#9fb0c0",fontFamily:"Arial",fontSize:"10px",backgroundColor:"#071019e8",padding:{x:7,y:5}}).setOrigin(0,1).setDepth(31);if(this.input.keyboard)this.keys=this.input.keyboard.addKeys("W,A,S,D,UP,DOWN,LEFT,RIGHT,E,SPACE,R") as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard?.on("keydown-E",()=>this.interact());this.input.keyboard?.on("keydown-SPACE",()=>this.interact());this.input.keyboard?.on("keydown-R",()=>this.reset());this.scale.on("resize",this.resize,this);this.reset();}update(_:number,d:number){if(this.state.mode!=="playing")return;const x=Number(Boolean(this.keys.D?.isDown||this.keys.RIGHT?.isDown))-Number(Boolean(this.keys.A?.isDown||this.keys.LEFT?.isDown)),y=Number(Boolean(this.keys.S?.isDown||this.keys.DOWN?.isDown))-Number(Boolean(this.keys.W?.isDown||this.keys.UP?.isDown));const r=advanceDataCenter(this.state,{x,y},d/1000);this.state=r.state;this.event(r.event);this.draw();}
 private projection(){const mobile=this.scale.width<620;if(!mobile)return{cameraX:DATA_CENTER_WORLD.width/2,cameraY:DATA_CENTER_WORLD.height/2,anchorX:this.scale.width/2,anchorY:this.scale.height/2+12,scale:Math.min((this.scale.width-42)/DATA_CENTER_WORLD.width,(this.scale.height-84)/DATA_CENTER_WORLD.height)};const scale=Math.max(.56,Math.min(.74,this.scale.width/535));return boundedWorldCamera({playerX:this.state.playerX,playerY:this.state.playerY,viewportWidth:this.scale.width,viewportHeight:this.scale.height,worldWidth:DATA_CENTER_WORLD.width,worldHeight:DATA_CENTER_WORLD.height,scale,anchorY:this.scale.height*.54});}
 private p(x:number,y:number){const c=this.projection();return{x:c.anchorX+(x-c.cameraX)*c.scale,y:c.anchorY+(y-c.cameraY)*c.scale};}
 private draw(){const g=this.g;if(!g)return;g.clear();g.fillStyle(BG,1).fillRect(0,0,this.scale.width,this.scale.height);const a=this.p(0,0),b=this.p(DATA_CENTER_WORLD.width,DATA_CENTER_WORLD.height),c=this.projection();g.fillStyle(FLOOR,1).fillRect(a.x,a.y,b.x-a.x,b.y-a.y);g.lineStyle(Math.max(.6,c.scale),GRID,.45);for(let x=0;x<=DATA_CENTER_WORLD.width;x+=80){const t=this.p(x,0),d=this.p(x,DATA_CENTER_WORLD.height);g.lineBetween(t.x,t.y,d.x,d.y);}for(let y=0;y<=DATA_CENTER_WORLD.height;y+=80){const l=this.p(0,y),r=this.p(DATA_CENTER_WORLD.width,y);g.lineBetween(l.x,l.y,r.x,r.y);}this.drawStaging();this.drawBays();this.drawStations();this.drawPlayer();const s=dataCenterStats(this.state),w=currentWorkload(this.state);this.left?.setText(`C ${s.compute}/${w.compute} · NET ${s.network}/${w.network} · ST ${s.storage}/${w.storage}\nPWR ${s.powerDraw}/${s.powerCapacity} · HEAT ${s.thermal}/${w.maxHeat} · RED ${s.redundancy}/${w.redundancy}`);this.right?.setText(`${clock(this.state.timeLeft)} RUN${this.state.workloadRunning?` · ${clock(this.state.workloadTime)} SLA`:""}\nDone ${this.state.completedWorkloads} · Rep ${Math.round(this.state.reputation)} · Best ${best}`);this.prompt?.setText(`${dataCenterPrompt(this.state)} · WASD/ARROWS + E`);this.detail?.setText(`${w.name.toUpperCase()}${dataCenterReady(this.state)?" · READY":" · BUILDING"}${this.state.faultSlot!==null?` · FAULT BAY ${this.state.faultSlot+1}`:""}\nUptime ${this.state.uptime.toFixed(0)}s · Breach ${this.state.slaBreaches.toFixed(1)}s · Score ${dataCenterScore(this.state)}`);mount.dataset.dcX=this.state.playerX.toFixed(1);mount.dataset.dcY=this.state.playerY.toFixed(1);mount.dataset.dcCarried=this.state.carried??"";mount.dataset.dcSlots=String(this.state.slots.filter(Boolean).length);mount.dataset.dcReady=dataCenterReady(this.state)?"true":"false";mount.dataset.dcRunning=this.state.workloadRunning?"true":"false";mount.dataset.dcCompleted=String(this.state.completedWorkloads);mount.dataset.dcFault=this.state.faultSlot===null?"":String(this.state.faultSlot);mount.dataset.dcKit=this.state.carryingRepairKit?"true":"false";mount.dataset.dcMode=this.state.mode;}
 private drawStaging(){for(const id of Object.keys(dataCenterLayout.staging) as RackType[]){const q=dataCenterLayout.staging[id],p=this.p(q.x,q.y),s=this.projection().scale;this.g?.fillStyle(COLORS[id],.15).fillRoundedRect(p.x-38*s,p.y-30*s,76*s,60*s,6);this.g?.lineStyle(2,COLORS[id],.8).strokeRoundedRect(p.x-38*s,p.y-30*s,76*s,60*s,6);}}
 private drawBays(){this.state.slots.forEach((id,i)=>{const q=dataCenterLayout.slots[i],p=this.p(q.x,q.y),s=this.projection().scale,fault=this.state.faultSlot===i;const color=id?COLORS[id]:0x516474;this.g?.fillStyle(0x09131c,.95).fillRoundedRect(p.x-48*s,p.y-64*s,96*s,128*s,7);this.g?.lineStyle(fault?4:2,fault?RED:color,fault?1:.75).strokeRoundedRect(p.x-48*s,p.y-64*s,96*s,128*s,7);if(id){for(let u=0;u<5;u++)this.g?.fillStyle(color,.65).fillRect(p.x-37*s,p.y+(-43+u*20)*s,74*s,9*s);}if(id==="compute"&&this.state.slots.some((v,j)=>v==="cooling"&&Math.hypot(dataCenterLayout.slots[j].x-q.x,dataCenterLayout.slots[j].y-q.y)<230))this.g?.lineStyle(2,CYAN,.55).strokeCircle(p.x,p.y,58*s);});}
 private drawStations(){const d=this.p(dataCenterLayout.deploy.x,dataCenterLayout.deploy.y),r=this.p(dataCenterLayout.repair.x,dataCenterLayout.repair.y),s=this.projection().scale;this.g?.fillStyle(GREEN,.12).fillCircle(d.x,d.y,46*s);this.g?.lineStyle(2,GREEN,.85).strokeCircle(d.x,d.y,46*s);this.g?.fillStyle(YELLOW,.12).fillCircle(r.x,r.y,46*s);this.g?.lineStyle(2,YELLOW,.85).strokeCircle(r.x,r.y,46*s);}
 private drawPlayer(){const p=this.p(this.state.playerX,this.state.playerY),s=this.projection().scale;this.g?.fillStyle(0x020405,.5).fillEllipse(p.x+2*s,p.y+12*s,22*s,8*s);this.g?.fillStyle(INK,1).fillCircle(p.x,p.y-2*s,11*s);if(this.state.carried)this.g?.fillStyle(COLORS[this.state.carried],1).fillRect(p.x+8*s,p.y-17*s,13*s,12*s);if(this.state.carryingRepairKit)this.g?.fillStyle(YELLOW,1).fillRect(p.x-21*s,p.y-17*s,12*s,10*s);}
 private interact(){const r=interactDataCenter(this.state);this.state=r.state;this.event(r.event);this.draw();}
 private event(e:DataCenterEvent){if(e==="rack_picked")tone(540);else if(e==="rack_placed"){tone(680);bridge.emit("game_action",{action:"rack_placed",slots:this.state.slots.filter(Boolean).length});}else if(e==="deploy_started"){tone(820,.12);bridge.emit("level_completed",{action:"workload_deployed",workload:currentWorkload(this.state).id});bridge.setStatus("Workload live — keep SLA capacity green while failures arrive");}else if(e==="deploy_blocked")tone(180);else if(e==="fault"){tone(145,.15);bridge.setStatus(`Rack fault in bay ${(this.state.faultSlot??0)+1} — get the repair kit`);}else if(e==="repair_started")tone(720);else if(e==="workload_complete")tone(880,.13);else if(e==="session_complete")this.end();}
 private end(){const score=dataCenterScore(this.state);best=Math.max(best,score);writeLocalGameValue(bridge.gameSlug,"high-score",1,best);bridge.emit("game_over",{score,completed_workloads:this.state.completedWorkloads,uptime:this.state.uptime,sla_breach_seconds:this.state.slaBreaches});bridge.setStatus(`Data center run complete · ${this.state.completedWorkloads} workloads · score ${score}`);}
 private reset(){this.state=createDataCenterState((Date.now()^0x45c0de)>>>0);this.draw();bridge.setStatus("Data Center Architect live — install racks, deploy workloads, and repair failures");bridge.emit("game_started",{mode:"walkable-data-center"});}private resize(){this.right?.setPosition(this.scale.width-14,12);this.prompt?.setPosition(this.scale.width/2,this.scale.height-12);this.detail?.setPosition(14,this.scale.height-12);this.draw();}}
 const game=new Phaser.Game({type:Phaser.AUTO,parent:mount,backgroundColor:BG,scene:[Scene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,pixelArt:false}});return{pause(){game.scene.pause("data-center-architect");bridge.setStatus("Paused");},resume(){game.scene.resume("data-center-architect");bridge.setStatus("Data Center Architect resumed");},restart(){game.scene.stop("data-center-architect");game.scene.start("data-center-architect");},setMuted(v:boolean){muted=v;},destroy(){game.destroy(true);void audio?.close();audio=null;}} satisfies GameRuntimeController;
}
