import Phaser from "phaser";
import { boundedWorldCamera } from "@/games/_shared/camera/worldCamera";
import { readLocalGameValue, writeLocalGameValue } from "@/games/_shared/storage/localGameStorage";
import type { GameBridge, GameRuntimeController } from "@/games/_shared/types/runtime";
import { FAB_FLOOR_WORLD, advanceFabFloor, createFabFloorState, fabFloorLayout, fabFloorPrompt, fabFloorScore, fabFloorYield, interactFabFloor, type FabFloorEvent, type FabFloorState, type FabToolId } from "./model";

const BG=0x071013,FLOOR=0x102126,GRID=0x1f3b40,INK=0xeaf5f3,GREEN=0x64e3b4,YELLOW=0xffce66,RED=0xff6f7f,CYAN=0x68d9ee;
const TOOL_COLORS: Record<FabToolId,number>={lithography:0xd59cff,etch:0x70d7ff,metrology:0x6be0ad};
function clock(s:number){const v=Math.max(0,Math.ceil(s));return `${Math.floor(v/60)}:${String(v%60).padStart(2,"0")}`;}
const FAB_TIERS=["PILOT LINE","RAMP LINE","VOLUME FAB","LIGHTS-OUT FAB"] as const;
function fabTier(score:number){return score>=6500?3:score>=3600?2:score>=1500?1:0;}

export function mountGame(mount:HTMLElement,bridge:GameBridge):GameRuntimeController{
 let muted=false;let audio:AudioContext|null=null;let best=readLocalGameValue<number>(bridge.gameSlug,"high-score",1)??0;
 const tone=(f:number,d=.07)=>{if(muted||typeof window==="undefined")return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d);}catch{}};
 class Scene extends Phaser.Scene{
  private state!:FabFloorState;private g?:Phaser.GameObjects.Graphics;private keys:Record<string,Phaser.Input.Keyboard.Key>={};private left?:Phaser.GameObjects.Text;private right?:Phaser.GameObjects.Text;private prompt?:Phaser.GameObjects.Text;private detail?:Phaser.GameObjects.Text;private visual=0;
  constructor(){super("fab-floor");}
  create(){this.g=this.add.graphics();this.left=this.add.text(14,12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",backgroundColor:"#071013df",padding:{x:8,y:5}}).setDepth(30);this.right=this.add.text(this.scale.width-14,12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",align:"right",backgroundColor:"#071013df",padding:{x:8,y:5}}).setOrigin(1,0).setDepth(30);this.prompt=this.add.text(this.scale.width/2,this.scale.height-12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"11px",fontStyle:"bold",backgroundColor:"#071013ef",padding:{x:8,y:5}}).setOrigin(.5,1).setDepth(31);this.detail=this.add.text(14,this.scale.height-12,"",{color:"#9bb0ad",fontFamily:"Arial",fontSize:"10px",backgroundColor:"#071013e8",padding:{x:7,y:5}}).setOrigin(0,1).setDepth(31);if(this.input.keyboard)this.keys=this.input.keyboard.addKeys("W,A,S,D,UP,DOWN,LEFT,RIGHT,E,SPACE,R") as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard?.on("keydown-E",()=>this.interact());this.input.keyboard?.on("keydown-SPACE",()=>this.interact());this.input.keyboard?.on("keydown-R",()=>this.reset());this.scale.on("resize",this.resize,this);this.reset();}
  update(_:number,delta:number){if(this.state.mode!=="playing")return;this.visual+=delta;const x=Number(Boolean(this.keys.D?.isDown||this.keys.RIGHT?.isDown))-Number(Boolean(this.keys.A?.isDown||this.keys.LEFT?.isDown));const y=Number(Boolean(this.keys.S?.isDown||this.keys.DOWN?.isDown))-Number(Boolean(this.keys.W?.isDown||this.keys.UP?.isDown));const r=advanceFabFloor(this.state,{x,y},delta/1000);this.state=r.state;this.event(r.event);this.draw();}
  private projection(){const mobile=this.scale.width<620;if(!mobile)return{cameraX:FAB_FLOOR_WORLD.width/2,cameraY:FAB_FLOOR_WORLD.height/2,anchorX:this.scale.width/2,anchorY:this.scale.height/2+12,scale:Math.min((this.scale.width-42)/FAB_FLOOR_WORLD.width,(this.scale.height-84)/FAB_FLOOR_WORLD.height)};const scale=Math.max(.58,Math.min(.76,this.scale.width/520));return boundedWorldCamera({playerX:this.state.playerX,playerY:this.state.playerY,viewportWidth:this.scale.width,viewportHeight:this.scale.height,worldWidth:FAB_FLOOR_WORLD.width,worldHeight:FAB_FLOOR_WORLD.height,scale,anchorY:this.scale.height*.54});}
  private p(x:number,y:number){const c=this.projection();return{x:c.anchorX+(x-c.cameraX)*c.scale,y:c.anchorY+(y-c.cameraY)*c.scale};}
  private draw(){const g=this.g;if(!g)return;g.clear();g.fillStyle(BG,1).fillRect(0,0,this.scale.width,this.scale.height);const a=this.p(0,0),b=this.p(FAB_FLOOR_WORLD.width,FAB_FLOOR_WORLD.height),c=this.projection();g.fillStyle(FLOOR,1).fillRect(a.x,a.y,b.x-a.x,b.y-a.y);g.lineStyle(Math.max(.6,c.scale),GRID,.45);for(let x=0;x<=FAB_FLOOR_WORLD.width;x+=80){const t=this.p(x,0),d=this.p(x,FAB_FLOOR_WORLD.height);g.lineBetween(t.x,t.y,d.x,d.y);}for(let y=0;y<=FAB_FLOOR_WORLD.height;y+=80){const l=this.p(0,y),r=this.p(FAB_FLOOR_WORLD.width,y);g.lineBetween(l.x,l.y,r.x,r.y);}this.drawEnvironment();this.drawRelease();this.drawTools();this.drawLots();this.drawMaintenance();this.drawPlayer();const q={lithography:0,etch:0,metrology:0};for(const lot of this.state.lots)q[lot.stage]++;this.left?.setText(`WIP ${this.state.lots.length} · L${q.lithography} E${q.etch} M${q.metrology}\nGood die ${Math.round(this.state.goodDie)} · Yield ${(fabFloorYield(this.state)*100).toFixed(1)}%`);this.right?.setText(`${clock(this.state.timeLeft)} SHIFT · ${FAB_TIERS[fabTier(best)]}\nRep ${Math.round(this.state.reputation)} · Cash ${this.state.cash.toFixed(0)} · Best ${best}`);this.prompt?.setText(`${fabFloorPrompt(this.state)} · WASD/ARROWS + E`);this.detail?.setText(`FOCUS ${this.state.focus.toUpperCase()}${this.state.carryingKit?" · KIT CARRIED":""}\nCompleted ${this.state.completedLots} · Score ${fabFloorScore(this.state)}`);mount.dataset.fabX=this.state.playerX.toFixed(1);mount.dataset.fabY=this.state.playerY.toFixed(1);mount.dataset.fabLots=String(this.state.lots.length);mount.dataset.fabCompleted=String(this.state.completedLots);mount.dataset.fabFocus=this.state.focus;mount.dataset.fabKit=this.state.carryingKit?"true":"false";mount.dataset.fabMode=this.state.mode;mount.dataset.fabAlarms=String(Object.values(this.state.tools).filter(t=>t.alarm).length);}
  private drawEnvironment(){const g=this.g;if(!g)return;const s=this.projection().scale,tier=fabTier(best),pulse=.55+.25*Math.sin(this.visual/420);
    const railA=this.p(250,118),railB=this.p(1110,118);g.lineStyle(7*s,0x233941,.9).lineBetween(railA.x,railA.y,railB.x,railB.y);g.lineStyle(2*s,CYAN,.35).lineBetween(railA.x,railA.y,railB.x,railB.y);
    const podX=300+((this.visual*.055)%(760));const pod=this.p(podX,118);g.fillStyle(CYAN,.85).fillRoundedRect(pod.x-15*s,pod.y-8*s,30*s,16*s,4*s);g.fillStyle(INK,.6).fillRect(pod.x-7*s,pod.y-3*s,14*s,5*s);
    const serviceTop=this.p(285,205),serviceBottom=this.p(1120,205);g.lineStyle(3*s,0x40616a,.55).lineBetween(serviceTop.x,serviceTop.y,serviceBottom.x,serviceBottom.y);
    for(let x=330;x<=1080;x+=94){const a=this.p(x,205),b=this.p(x,232);g.lineStyle(2*s,0x40616a,.45).lineBetween(a.x,a.y,b.x,b.y);}
    const aisle1a=this.p(285,475),aisle1b=this.p(1125,475);g.lineStyle(2*s,YELLOW,.24).lineBetween(aisle1a.x,aisle1a.y,aisle1b.x,aisle1b.y);
    for(let x=305;x<1110;x+=68){const a=this.p(x,468),b=this.p(x+28,482);g.lineStyle(2*s,YELLOW,.18).lineBetween(a.x,a.y,b.x,b.y);}
    const gown=this.p(165,125);g.fillStyle(0x152a30,.95).fillRoundedRect(gown.x-58*s,gown.y-36*s,116*s,72*s,7*s);g.lineStyle(2*s,GREEN,.42).strokeRoundedRect(gown.x-58*s,gown.y-36*s,116*s,72*s,7*s);
    for(let i=0;i<3+tier;i++){const q=this.p(318+i*148,682);g.fillStyle(0x172b31,.95).fillRoundedRect(q.x-48*s,q.y-21*s,96*s,42*s,5*s);g.lineStyle(1.5*s,tier>=2?GREEN:GRID,.45).strokeRoundedRect(q.x-48*s,q.y-21*s,96*s,42*s,5*s);g.fillStyle(tier>=3?GREEN:CYAN,.25+pulse*.25).fillCircle(q.x+30*s,q.y,4*s);}
    if(tier>=1){for(let i=0;i<2+tier;i++){const q=this.p(420+i*188,72);g.fillStyle(GREEN,.16+pulse*.12).fillCircle(q.x,q.y,8*s);g.lineStyle(1*s,GREEN,.35).strokeCircle(q.x,q.y,12*s);}}
  }
  private drawRelease(){const p=this.p(fabFloorLayout.release.x,fabFloorLayout.release.y),s=this.projection().scale,g=this.g;if(!g)return;g.fillStyle(0x18272d,.95).fillRoundedRect(p.x-42*s,p.y-48*s,84*s,96*s,7*s);g.lineStyle(2,YELLOW,.75).strokeRoundedRect(p.x-42*s,p.y-48*s,84*s,96*s,7*s);for(let i=0;i<3;i++){const y=p.y+(-25+i*25)*s;g.fillStyle(0x2a424a,.95).fillRoundedRect(p.x-27*s,y-7*s,54*s,14*s,3*s);g.fillStyle(i===0?YELLOW:CYAN,.55).fillCircle(p.x+19*s,y,3*s);}g.fillStyle(YELLOW,.18).fillCircle(p.x,p.y,52*s);}
  private drawTools(){const g=this.g;if(!g)return;for(const id of ["lithography","etch","metrology"] as FabToolId[]){const r=fabFloorLayout.tools[id],a=this.p(r.x,r.y),b=this.p(r.x+r.width,r.y+r.height),tool=this.state.tools[id],color=tool.alarm?RED:TOOL_COLORS[id],s=this.projection().scale,w=b.x-a.x,h=b.y-a.y;g.fillStyle(0x132a31,1).fillRoundedRect(a.x,a.y,w,h,9);g.fillStyle(0x1e3940,1).fillRoundedRect(a.x+8*s,a.y+9*s,w-16*s,h-18*s,6);g.lineStyle(tool.alarm?4:2,color,.9).strokeRoundedRect(a.x,a.y,w,h,9);
      const center=this.p(r.x+r.width/2,r.y+r.height/2);g.fillStyle(0x0a161a,.9).fillCircle(center.x-22*s,center.y,26*s);g.lineStyle(3*s,color,.55).strokeCircle(center.x-22*s,center.y,22*s);g.fillStyle(color,.15+.08*Math.sin(this.visual/260)).fillCircle(center.x-22*s,center.y,15*s);
      g.fillStyle(0x071013,.9).fillRoundedRect(center.x+16*s,center.y-28*s,53*s,34*s,4*s);g.fillStyle(color,.5).fillRect(center.x+23*s,center.y-19*s,38*s,4*s);g.fillStyle(tool.health>70?GREEN:tool.health>45?YELLOW:RED,.7).fillRect(center.x+23*s,center.y-7*s,38*s*Math.max(0,Math.min(1,tool.health/100)),4*s);
      g.fillStyle(tool.alarm?RED:tool.maintenance>0?YELLOW:GREEN,tool.alarm?.95:.8).fillCircle(center.x+56*s,center.y+27*s,5*s);g.fillStyle(0x0b1b20,.9).fillRoundedRect(center.x+14*s,center.y+19*s,40*s,18*s,3*s);
      if(this.state.focus===id)g.lineStyle(3,YELLOW,.7).strokeCircle(center.x,center.y,66*s);if(tool.alarm){g.lineStyle(3,RED,.35+.35*Math.sin(this.visual/120)).strokeCircle(center.x,center.y,76*s);}
    }}
  private drawLots(){const g=this.g;if(!g)return;const counts:Record<FabToolId,number>={lithography:0,etch:0,metrology:0};for(const lot of this.state.lots){const r=fabFloorLayout.tools[lot.stage],i=counts[lot.stage]++,base=this.p(r.x-48+i%4*30,r.y+r.height+35+Math.floor(i/4)*23),s=this.projection().scale;g.fillStyle(0x18343b,.98).fillRoundedRect(base.x-13*s,base.y-8*s,26*s,16*s,3*s);g.lineStyle(1.5*s,CYAN,.8).strokeRoundedRect(base.x-13*s,base.y-8*s,26*s,16*s,3*s);g.lineStyle(2*s,CYAN,.55).lineBetween(base.x-7*s,base.y-8*s,base.x-7*s,base.y-13*s);g.lineBetween(base.x+7*s,base.y-8*s,base.x+7*s,base.y-13*s);g.lineBetween(base.x-7*s,base.y-13*s,base.x+7*s,base.y-13*s);g.fillStyle(lot.quality>.94?GREEN:YELLOW,.8).fillRect(base.x-8*s,base.y-2*s,16*s*Math.max(.15,lot.progress),3*s);}}
  private drawMaintenance(){const p=this.p(fabFloorLayout.maintenance.x,fabFloorLayout.maintenance.y),s=this.projection().scale,g=this.g;if(!g)return;g.fillStyle(0x182d32,.98).fillRoundedRect(p.x-43*s,p.y-37*s,86*s,74*s,7*s);g.lineStyle(2,GREEN,.7).strokeRoundedRect(p.x-43*s,p.y-37*s,86*s,74*s,7*s);for(let i=0;i<3;i++){g.fillStyle(0x29464c,.9).fillRect(p.x-29*s,p.y+(-20+i*19)*s,58*s,9*s);g.fillStyle(GREEN,.55).fillCircle(p.x+23*s,p.y+(-16+i*19)*s,3*s);}g.fillStyle(GREEN,.1).fillCircle(p.x,p.y,53*s);}
  private drawPlayer(){const p=this.p(this.state.playerX,this.state.playerY),s=this.projection().scale,g=this.g;if(!g)return;g.fillStyle(0x020405,.45).fillEllipse(p.x+2*s,p.y+13*s,27*s,9*s);g.fillStyle(0xdcebee,1).fillRoundedRect(p.x-10*s,p.y-8*s,20*s,27*s,7*s);g.fillStyle(INK,1).fillCircle(p.x,p.y-12*s,10*s);g.fillStyle(0x5f7b83,.9).fillRoundedRect(p.x-7*s,p.y-15*s,14*s,7*s,3*s);g.lineStyle(2*s,0xb9d7df,.8).lineBetween(p.x-8*s,p.y+17*s,p.x-9*s,p.y+24*s);g.lineBetween(p.x+8*s,p.y+17*s,p.x+9*s,p.y+24*s);if(this.state.carryingKit){g.fillStyle(YELLOW,1).fillRoundedRect(p.x+10*s,p.y-5*s,13*s,11*s,2*s);g.lineStyle(1*s,0x5b4a1c,.8).strokeRoundedRect(p.x+10*s,p.y-5*s,13*s,11*s,2*s);}}
  private interact(){const r=interactFabFloor(this.state);this.state=r.state;this.event(r.event);this.draw();}
  private event(e:FabFloorEvent){if(e==="lot_released"){tone(520);bridge.emit("game_action",{action:"lot_released",wip:this.state.lots.length});}else if(e==="kit_picked")tone(650);else if(e==="maintenance_started"){tone(760);bridge.emit("game_action",{action:"maintenance_started"});}else if(e==="focus_changed")tone(580);else if(e==="alarm"){tone(165,.14);bridge.setStatus("Tool alarm — get a maintenance kit and reach the flashing tool");}else if(e==="lot_completed")tone(820);else if(e==="shift_complete")this.end();}
  private end(){const score=fabFloorScore(this.state),oldTier=fabTier(best);best=Math.max(best,score);const newTier=fabTier(best);writeLocalGameValue(bridge.gameSlug,"high-score",1,best);bridge.emit("game_over",{score,good_die:this.state.goodDie,yield:fabFloorYield(this.state),completed_lots:this.state.completedLots,facility_tier:newTier});if(newTier>oldTier){bridge.emit("game_action",{action:"facility_tier_up",tier:newTier});bridge.setStatus(`Facility upgraded — ${FAB_TIERS[newTier]} unlocked for future shifts`);}else bridge.setStatus(`Fab shift complete · ${this.state.completedLots} lots · score ${score}`);}
  private reset(){const tier=fabTier(best),next=createFabFloorState((Date.now()^0x51f15e)>>>0);next.cash+=tier*6;for(const id of ["lithography","etch","metrology"] as FabToolId[])next.tools[id].health=Math.min(100,next.tools[id].health+tier*2);this.state=next;this.draw();bridge.setStatus(`Fab Floor live — ${FAB_TIERS[tier]} · release lots, chase bottlenecks, and service tool alarms`);bridge.emit("game_started",{mode:"walkable-fab-shift",facility_tier:tier});}
  private resize(){this.right?.setPosition(this.scale.width-14,12);this.prompt?.setPosition(this.scale.width/2,this.scale.height-12);this.detail?.setPosition(14,this.scale.height-12);this.draw();}
 }
 const game=new Phaser.Game({type:Phaser.AUTO,parent:mount,backgroundColor:BG,scene:[Scene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,pixelArt:false}});
 return{pause(){game.scene.pause("fab-floor");bridge.setStatus("Paused");},resume(){game.scene.resume("fab-floor");bridge.setStatus("Fab Floor resumed");},restart(){game.scene.stop("fab-floor");game.scene.start("fab-floor");},setMuted(v:boolean){muted=v;},destroy(){game.destroy(true);void audio?.close();audio=null;}} satisfies GameRuntimeController;
}
