import Phaser from "phaser";
import { boundedWorldCamera } from "@/games/_shared/camera/worldCamera";
import { readLocalGameValue, writeLocalGameValue } from "@/games/_shared/storage/localGameStorage";
import type { GameBridge, GameRuntimeController } from "@/games/_shared/types/runtime";
import { FAB_FLOOR_WORLD, advanceFabFloor, createFabFloorState, fabFloorLayout, fabFloorPrompt, fabFloorScore, fabFloorYield, interactFabFloor, type FabFloorEvent, type FabFloorState, type FabToolId } from "./model";

const BG=0x071013,FLOOR=0x102126,GRID=0x1f3b40,INK=0xeaf5f3,GREEN=0x64e3b4,YELLOW=0xffce66,RED=0xff6f7f,CYAN=0x68d9ee;
const TOOL_COLORS: Record<FabToolId,number>={lithography:0xd59cff,etch:0x70d7ff,metrology:0x6be0ad};
function clock(s:number){const v=Math.max(0,Math.ceil(s));return `${Math.floor(v/60)}:${String(v%60).padStart(2,"0")}`;}

export function mountGame(mount:HTMLElement,bridge:GameBridge):GameRuntimeController{
 let muted=false;let audio:AudioContext|null=null;let best=readLocalGameValue<number>(bridge.gameSlug,"high-score",1)??0;
 const tone=(f:number,d=.07)=>{if(muted||typeof window==="undefined")return;try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d);}catch{}};
 class Scene extends Phaser.Scene{
  private state!:FabFloorState;private g?:Phaser.GameObjects.Graphics;private keys:Record<string,Phaser.Input.Keyboard.Key>={};private left?:Phaser.GameObjects.Text;private right?:Phaser.GameObjects.Text;private prompt?:Phaser.GameObjects.Text;private detail?:Phaser.GameObjects.Text;private visual=0;
  constructor(){super("fab-floor");}
  create(){this.g=this.add.graphics();this.left=this.add.text(14,12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",backgroundColor:"#071013df",padding:{x:8,y:5}}).setDepth(30);this.right=this.add.text(this.scale.width-14,12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"13px",fontStyle:"bold",align:"right",backgroundColor:"#071013df",padding:{x:8,y:5}}).setOrigin(1,0).setDepth(30);this.prompt=this.add.text(this.scale.width/2,this.scale.height-12,"",{color:"#eaf5f3",fontFamily:"Arial",fontSize:"11px",fontStyle:"bold",backgroundColor:"#071013ef",padding:{x:8,y:5}}).setOrigin(.5,1).setDepth(31);this.detail=this.add.text(14,this.scale.height-12,"",{color:"#9bb0ad",fontFamily:"Arial",fontSize:"10px",backgroundColor:"#071013e8",padding:{x:7,y:5}}).setOrigin(0,1).setDepth(31);if(this.input.keyboard)this.keys=this.input.keyboard.addKeys("W,A,S,D,UP,DOWN,LEFT,RIGHT,E,SPACE,R") as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard?.on("keydown-E",()=>this.interact());this.input.keyboard?.on("keydown-SPACE",()=>this.interact());this.input.keyboard?.on("keydown-R",()=>this.reset());this.scale.on("resize",this.resize,this);this.reset();}
  update(_:number,delta:number){if(this.state.mode!=="playing")return;this.visual+=delta;let x=Number(Boolean(this.keys.D?.isDown||this.keys.RIGHT?.isDown))-Number(Boolean(this.keys.A?.isDown||this.keys.LEFT?.isDown));let y=Number(Boolean(this.keys.S?.isDown||this.keys.DOWN?.isDown))-Number(Boolean(this.keys.W?.isDown||this.keys.UP?.isDown));const r=advanceFabFloor(this.state,{x,y},delta/1000);this.state=r.state;this.event(r.event);this.draw();}
  private projection(){const mobile=this.scale.width<620;if(!mobile)return{cameraX:FAB_FLOOR_WORLD.width/2,cameraY:FAB_FLOOR_WORLD.height/2,anchorX:this.scale.width/2,anchorY:this.scale.height/2+12,scale:Math.min((this.scale.width-42)/FAB_FLOOR_WORLD.width,(this.scale.height-84)/FAB_FLOOR_WORLD.height)};const scale=Math.max(.58,Math.min(.76,this.scale.width/520));return boundedWorldCamera({playerX:this.state.playerX,playerY:this.state.playerY,viewportWidth:this.scale.width,viewportHeight:this.scale.height,worldWidth:FAB_FLOOR_WORLD.width,worldHeight:FAB_FLOOR_WORLD.height,scale,anchorY:this.scale.height*.54});}
  private p(x:number,y:number){const c=this.projection();return{x:c.anchorX+(x-c.cameraX)*c.scale,y:c.anchorY+(y-c.cameraY)*c.scale};}
  private draw(){const g=this.g;if(!g)return;g.clear();g.fillStyle(BG,1).fillRect(0,0,this.scale.width,this.scale.height);const a=this.p(0,0),b=this.p(FAB_FLOOR_WORLD.width,FAB_FLOOR_WORLD.height),c=this.projection();g.fillStyle(FLOOR,1).fillRect(a.x,a.y,b.x-a.x,b.y-a.y);g.lineStyle(Math.max(.6,c.scale),GRID,.45);for(let x=0;x<=FAB_FLOOR_WORLD.width;x+=80){const t=this.p(x,0),d=this.p(x,FAB_FLOOR_WORLD.height);g.lineBetween(t.x,t.y,d.x,d.y);}for(let y=0;y<=FAB_FLOOR_WORLD.height;y+=80){const l=this.p(0,y),r=this.p(FAB_FLOOR_WORLD.width,y);g.lineBetween(l.x,l.y,r.x,r.y);}this.drawRelease();this.drawTools();this.drawLots();this.drawMaintenance();this.drawPlayer();const q={lithography:0,etch:0,metrology:0};for(const lot of this.state.lots)q[lot.stage]++;this.left?.setText(`WIP ${this.state.lots.length} · L${q.lithography} E${q.etch} M${q.metrology}\nGood die ${Math.round(this.state.goodDie)} · Yield ${(fabFloorYield(this.state)*100).toFixed(1)}%`);this.right?.setText(`${clock(this.state.timeLeft)} SHIFT\nRep ${Math.round(this.state.reputation)} · Cash ${this.state.cash.toFixed(0)} · Best ${best}`);this.prompt?.setText(`${fabFloorPrompt(this.state)} · WASD/ARROWS + E`);this.detail?.setText(`FOCUS ${this.state.focus.toUpperCase()}${this.state.carryingKit?" · KIT CARRIED":""}\nCompleted ${this.state.completedLots} · Score ${fabFloorScore(this.state)}`);mount.dataset.fabX=this.state.playerX.toFixed(1);mount.dataset.fabY=this.state.playerY.toFixed(1);mount.dataset.fabLots=String(this.state.lots.length);mount.dataset.fabCompleted=String(this.state.completedLots);mount.dataset.fabFocus=this.state.focus;mount.dataset.fabKit=this.state.carryingKit?"true":"false";mount.dataset.fabMode=this.state.mode;mount.dataset.fabAlarms=String(Object.values(this.state.tools).filter(t=>t.alarm).length);}
  private drawRelease(){const p=this.p(fabFloorLayout.release.x,fabFloorLayout.release.y),s=this.projection().scale;this.g?.fillStyle(YELLOW,.14).fillCircle(p.x,p.y,42*s);this.g?.lineStyle(2,YELLOW,.85).strokeCircle(p.x,p.y,42*s);}
  private drawTools(){for(const id of ["lithography","etch","metrology"] as FabToolId[]){const r=fabFloorLayout.tools[id],a=this.p(r.x,r.y),b=this.p(r.x+r.width,r.y+r.height),tool=this.state.tools[id],color=tool.alarm?RED:TOOL_COLORS[id];this.g?.fillStyle(0x173139,1).fillRoundedRect(a.x,a.y,b.x-a.x,b.y-a.y,8);this.g?.lineStyle(tool.alarm?4:2,color,.9).strokeRoundedRect(a.x,a.y,b.x-a.x,b.y-a.y,8);const center=this.p(r.x+r.width/2,r.y+r.height/2);this.g?.fillStyle(color,.16).fillCircle(center.x,center.y,45*this.projection().scale);if(this.state.focus===id)this.g?.lineStyle(3,YELLOW,.7).strokeCircle(center.x,center.y,58*this.projection().scale);}}
  private drawLots(){const counts:Record<FabToolId,number>={lithography:0,etch:0,metrology:0};for(const lot of this.state.lots){const r=fabFloorLayout.tools[lot.stage],i=counts[lot.stage]++,base=this.p(r.x-42+i%4*22,r.y+r.height+34+Math.floor(i/4)*18),s=this.projection().scale;this.g?.fillStyle(CYAN,.95).fillRoundedRect(base.x-9*s,base.y-5*s,18*s,10*s,2);}}
  private drawMaintenance(){const p=this.p(fabFloorLayout.maintenance.x,fabFloorLayout.maintenance.y),s=this.projection().scale;this.g?.fillStyle(GREEN,.12).fillCircle(p.x,p.y,43*s);this.g?.lineStyle(2,GREEN,.8).strokeCircle(p.x,p.y,43*s);}
  private drawPlayer(){const p=this.p(this.state.playerX,this.state.playerY),s=this.projection().scale;this.g?.fillStyle(0x020405,.5).fillEllipse(p.x+2*s,p.y+11*s,22*s,8*s);this.g?.fillStyle(INK,1).fillCircle(p.x,p.y-2*s,11*s);if(this.state.carryingKit)this.g?.fillStyle(YELLOW,1).fillRect(p.x+9*s,p.y-14*s,11*s,9*s);}
  private interact(){const r=interactFabFloor(this.state);this.state=r.state;this.event(r.event);this.draw();}
  private event(e:FabFloorEvent){if(e==="lot_released"){tone(520);bridge.emit("game_action",{action:"lot_released",wip:this.state.lots.length});}else if(e==="kit_picked")tone(650);else if(e==="maintenance_started"){tone(760);bridge.emit("game_action",{action:"maintenance_started"});}else if(e==="focus_changed")tone(580);else if(e==="alarm"){tone(165,.14);bridge.setStatus("Tool alarm — get a maintenance kit and reach the flashing tool");}else if(e==="lot_completed")tone(820);else if(e==="shift_complete")this.end();}
  private end(){const score=fabFloorScore(this.state);best=Math.max(best,score);writeLocalGameValue(bridge.gameSlug,"high-score",1,best);bridge.emit("game_over",{score,good_die:this.state.goodDie,yield:fabFloorYield(this.state),completed_lots:this.state.completedLots});bridge.setStatus(`Fab shift complete · ${this.state.completedLots} lots · score ${score}`);}
  private reset(){this.state=createFabFloorState((Date.now()^0x51f15e)>>>0);this.draw();bridge.setStatus("Fab Floor live — release lots, chase bottlenecks, and service tool alarms");bridge.emit("game_started",{mode:"walkable-fab-shift"});}
  private resize(){this.right?.setPosition(this.scale.width-14,12);this.prompt?.setPosition(this.scale.width/2,this.scale.height-12);this.detail?.setPosition(14,this.scale.height-12);this.draw();}
 }
 const game=new Phaser.Game({type:Phaser.AUTO,parent:mount,backgroundColor:BG,scene:[Scene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,pixelArt:false}});
 return{pause(){game.scene.pause("fab-floor");bridge.setStatus("Paused");},resume(){game.scene.resume("fab-floor");bridge.setStatus("Fab Floor resumed");},restart(){game.scene.stop("fab-floor");game.scene.start("fab-floor");},setMuted(v:boolean){muted=v;},destroy(){game.destroy(true);void audio?.close();audio=null;}} satisfies GameRuntimeController;
}
